// Write deploy/web/headers.json: the production headers for whatever serves
// the built web apps (UO-120). Host-agnostic on purpose: the deploy story turns
// this into nginx, CDN or Cloud Run configuration. CI regenerates it and fails
// if it differs from what is committed.
//
//   node tools/app-config/generate-headers.mjs
import { mkdir, writeFile } from 'node:fs/promises'
import { dirname, join } from 'node:path'
import { fileURLToPath } from 'node:url'

import { PROD_CONNECT, PROD_IMAGES, RECAPTCHA_ORIGINS, securityHeaders } from './headers.mjs'

const root = join(dirname(fileURLToPath(import.meta.url)), '..', '..')
const out = join(root, 'deploy', 'web', 'headers.json')

// The CAPTCHA widget is platform-wide: public forms exist in every app, so
// the served policy allows it everywhere.
const headers = securityHeaders({
  connect: PROD_CONNECT,
  images: PROD_IMAGES,
  captcha: RECAPTCHA_ORIGINS,
  providers: true,
})
const body = {
  $comment:
    'Generated by tools/app-config/generate-headers.mjs; never edit. __API_ORIGIN__, __REALTIME_ORIGIN__, __IMAGE_ORIGIN__, __STORAGE_ORIGIN__ and __ERROR_ORIGIN__ are replaced at deploy; the __PROVIDER_*__ placeholders by the org’s provider origins, per page served, from the rtc service, or dropped.',
  headers,
}
await mkdir(dirname(out), { recursive: true })
await writeFile(out, JSON.stringify(body, null, 2) + '\n')
console.log(`wrote ${out}`)
