// Write deploy/web/headers.json: the production headers for whatever serves
// the built web apps (UO-120). Host-agnostic on purpose: the deploy story turns
// this into nginx, CDN or Cloud Run configuration. CI regenerates it and fails
// if it differs from what is committed.
//
//   node tools/app-config/generate-headers.mjs
import { mkdir, writeFile } from 'node:fs/promises'
import { dirname, join } from 'node:path'
import { fileURLToPath } from 'node:url'

import {
  PROD_CONNECT,
  PROD_IMAGES,
  PRODUCT_SECURITY,
  RECAPTCHA_ORIGINS,
  securityHeaders,
} from './headers.mjs'

const root = join(dirname(fileURLToPath(import.meta.url)), '..', '..')
const out = join(root, 'deploy', 'web', 'headers.json')

/** The production headers every kept app is served with. */
export function productionHeaders() {
  // The CAPTCHA widget is platform-wide: public forms exist in every app, so
  // the served policy allows it everywhere. The product's own additions come
  // from the product config.
  return securityHeaders({
    connect: PROD_CONNECT,
    images: PROD_IMAGES,
    captcha: RECAPTCHA_ORIGINS,
    product: PRODUCT_SECURITY,
  })
}

if (process.argv[1] === fileURLToPath(import.meta.url)) {
  const body = {
    $comment:
      'Generated by tools/app-config/generate-headers.mjs; never edit. __API_ORIGIN__, __ERROR_ORIGIN__ and __STORAGE_ORIGIN__ are replaced at deploy, or dropped.',
    headers: productionHeaders(),
  }
  await mkdir(dirname(out), { recursive: true })
  await writeFile(out, JSON.stringify(body, null, 2) + '\n')
  console.log(`wrote ${out}`)
}
