// Build a release APK on this machine and, with --install, put it on the
// Android device plugged in over USB. No store account, no signing service:
// the debug keystore Android Studio ships signs it, which is enough for a
// device that allows installs from a computer.
//
//   node tools/apk.mjs             android/app/build/outputs/apk/release/app-release.apk
//   node tools/apk.mjs --install   ... and adb install -r it
//
// Needs the Android SDK (ANDROID_HOME) and a JDK 17+. The native project is
// generated by `expo prebuild` and is not committed; delete android/ to
// regenerate it after a config change.
import { spawnSync } from 'node:child_process'
import { existsSync, readdirSync } from 'node:fs'
import { dirname, join } from 'node:path'
import { fileURLToPath } from 'node:url'

const app = join(dirname(fileURLToPath(import.meta.url)), '..')
const android = join(app, 'android')
const apk = join(android, 'app', 'build', 'outputs', 'apk', 'release', 'app-release.apk')
const windows = process.platform === 'win32'

// Gradle needs a JDK, not the launcher Windows puts on PATH. A stale
// JAVA_HOME (an uninstalled JDK) is replaced by one this machine has:
// Android Studio's bundled JDK, or an installed JDK 17+.
const env = { ...process.env }
const isJdk = (dir) => Boolean(dir) && existsSync(join(dir, 'bin', windows ? 'javac.exe' : 'javac'))
if (!isJdk(env.JAVA_HOME)) {
  const candidates = windows
    ? [
        join(env.ProgramFiles ?? 'C:\\Program Files', 'Android', 'Android Studio', 'jbr'),
        ...safeList(join(env.ProgramFiles ?? 'C:\\Program Files', 'Java')).map((d) =>
          join(env.ProgramFiles ?? 'C:\\Program Files', 'Java', d),
        ),
      ]
    : [
        '/Applications/Android Studio.app/Contents/jbr/Contents/Home',
        ...safeList('/usr/lib/jvm').map((d) => join('/usr/lib/jvm', d)),
      ]
  const found = candidates.find(isJdk)
  if (!found) {
    console.error('no JDK found: set JAVA_HOME to a JDK 17 or newer')
    process.exit(1)
  }
  console.warn(`JAVA_HOME is not a JDK; using ${found}`)
  env.JAVA_HOME = found
}

function safeList(dir) {
  try {
    return readdirSync(dir)
  } catch {
    return []
  }
}

function run(command, args, cwd) {
  const result = spawnSync(command, args, { cwd, stdio: 'inherit', shell: windows, env })
  if (result.status !== 0) process.exit(result.status ?? 1)
}

if (!existsSync(join(android, 'gradlew'))) {
  run('npx', ['expo', 'prebuild', '--platform', 'android', '--no-install'], app)
}
// By its full path: cmd.exe, which runs it on Windows, does not look in the
// working directory for a bare name passed this way.
run(join(android, windows ? 'gradlew.bat' : 'gradlew'), ['assembleRelease', '--quiet'], android)
console.log(`apk: ${apk}`)

if (process.argv.includes('--install')) {
  run('adb', ['install', '-r', apk], app)
  console.log('installed on the connected device')
}
